// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BQDepositsAPIService is a service that implements the logic for the BQDepositsAPIServicer
// This service should implement the business logic for every endpoint for the BQDepositsAPI API.
// Include any external packages or services that will be required by this service.
type BQDepositsAPIService struct {
}

// NewBQDepositsAPIService creates a default api service
func NewBQDepositsAPIService() *BQDepositsAPIService {
	return &BQDepositsAPIService{}
}

// InitiateDeposits - InBQ Instantiate a new Deposits
func (s *BQDepositsAPIService) InitiateDeposits(ctx context.Context, leasingid string, deposits Deposits) (ImplResponse, error) {
	// TODO - update InitiateDeposits with the required logic for this service method.
	// Add api_bq_deposits_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Deposits{}) or use other options such as http.Ok ...
	// return Response(200, Deposits{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("InitiateDeposits method not implemented")
}

// RetrieveDeposits - ReBQ Retrieve details about any aspect of Deposits
func (s *BQDepositsAPIService) RetrieveDeposits(ctx context.Context, leasingid string, depositsid string) (ImplResponse, error) {
	// TODO - update RetrieveDeposits with the required logic for this service method.
	// Add api_bq_deposits_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Deposits{}) or use other options such as http.Ok ...
	// return Response(200, Deposits{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveDeposits method not implemented")
}

// UpdateDeposits - UpBQ Update details relating to Deposits
func (s *BQDepositsAPIService) UpdateDeposits(ctx context.Context, leasingid string, depositsid string, deposits Deposits) (ImplResponse, error) {
	// TODO - update UpdateDeposits with the required logic for this service method.
	// Add api_bq_deposits_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Deposits{}) or use other options such as http.Ok ...
	// return Response(200, Deposits{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateDeposits method not implemented")
}
