// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BQCollateralAPIService is a service that implements the logic for the BQCollateralAPIServicer
// This service should implement the business logic for every endpoint for the BQCollateralAPI API.
// Include any external packages or services that will be required by this service.
type BQCollateralAPIService struct {
}

// NewBQCollateralAPIService creates a default api service
func NewBQCollateralAPIService() *BQCollateralAPIService {
	return &BQCollateralAPIService{}
}

// InitiateCollateral - InBQ Instantiate a new Collateral
func (s *BQCollateralAPIService) InitiateCollateral(ctx context.Context, leasingid string, collateral Collateral) (ImplResponse, error) {
	// TODO - update InitiateCollateral with the required logic for this service method.
	// Add api_bq_collateral_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Collateral{}) or use other options such as http.Ok ...
	// return Response(200, Collateral{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("InitiateCollateral method not implemented")
}

// RetrieveCollateral - ReBQ Retrieve details about any aspect of Collateral
func (s *BQCollateralAPIService) RetrieveCollateral(ctx context.Context, leasingid string, collateralid string) (ImplResponse, error) {
	// TODO - update RetrieveCollateral with the required logic for this service method.
	// Add api_bq_collateral_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Collateral{}) or use other options such as http.Ok ...
	// return Response(200, Collateral{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveCollateral method not implemented")
}

// RequestCollateral - RqBQ Request manual intervention or a decision with respect to Collateral
func (s *BQCollateralAPIService) RequestCollateral(ctx context.Context, leasingid string, collateralid string, collateral Collateral) (ImplResponse, error) {
	// TODO - update RequestCollateral with the required logic for this service method.
	// Add api_bq_collateral_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Collateral{}) or use other options such as http.Ok ...
	// return Response(200, Collateral{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequestCollateral method not implemented")
}

// UpdateCollateral - UpBQ Update details relating to Collateral
func (s *BQCollateralAPIService) UpdateCollateral(ctx context.Context, leasingid string, collateralid string, collateral Collateral) (ImplResponse, error) {
	// TODO - update UpdateCollateral with the required logic for this service method.
	// Add api_bq_collateral_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Collateral{}) or use other options such as http.Ok ...
	// return Response(200, Collateral{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateCollateral method not implemented")
}
