// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BQInterestAPIService is a service that implements the logic for the BQInterestAPIServicer
// This service should implement the business logic for every endpoint for the BQInterestAPI API.
// Include any external packages or services that will be required by this service.
type BQInterestAPIService struct {
}

// NewBQInterestAPIService creates a default api service
func NewBQInterestAPIService() *BQInterestAPIService {
	return &BQInterestAPIService{}
}

// RetrieveInterest - ReBQ Retrieve details about any aspect of Interest
func (s *BQInterestAPIService) RetrieveInterest(ctx context.Context, leasingid string, interestid string) (ImplResponse, error) {
	// TODO - update RetrieveInterest with the required logic for this service method.
	// Add api_bq_interest_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Interest{}) or use other options such as http.Ok ...
	// return Response(200, Interest{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveInterest method not implemented")
}

// UpdateInterest - UpBQ Update details relating to Interest
func (s *BQInterestAPIService) UpdateInterest(ctx context.Context, leasingid string, interestid string, interest Interest) (ImplResponse, error) {
	// TODO - update UpdateInterest with the required logic for this service method.
	// Add api_bq_interest_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Interest{}) or use other options such as http.Ok ...
	// return Response(200, Interest{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateInterest method not implemented")
}
