// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BQClearingandSettlementAPIService is a service that implements the logic for the BQClearingandSettlementAPIServicer
// This service should implement the business logic for every endpoint for the BQClearingandSettlementAPI API.
// Include any external packages or services that will be required by this service.
type BQClearingandSettlementAPIService struct {
}

// NewBQClearingandSettlementAPIService creates a default api service
func NewBQClearingandSettlementAPIService() *BQClearingandSettlementAPIService {
	return &BQClearingandSettlementAPIService{}
}

// RetrieveClearingandSettlement - ReBQ Retrieve details about any aspect of Clearing and Settlement
func (s *BQClearingandSettlementAPIService) RetrieveClearingandSettlement(ctx context.Context, leasingid string, clearingandsettlementid string) (ImplResponse, error) {
	// TODO - update RetrieveClearingandSettlement with the required logic for this service method.
	// Add api_bq_clearingand_settlement_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ClearingandSettlement{}) or use other options such as http.Ok ...
	// return Response(200, ClearingandSettlement{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RetrieveClearingandSettlement method not implemented")
}

// UpdateClearingandSettlement - UpBQ Update details relating to Clearing and Settlement
func (s *BQClearingandSettlementAPIService) UpdateClearingandSettlement(ctx context.Context, leasingid string, clearingandsettlementid string, clearingandSettlement ClearingandSettlement) (ImplResponse, error) {
	// TODO - update UpdateClearingandSettlement with the required logic for this service method.
	// Add api_bq_clearingand_settlement_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ClearingandSettlement{}) or use other options such as http.Ok ...
	// return Response(200, ClearingandSettlement{}), nil

	// TODO: Uncomment the next line to return response Response(400, HttpError{}) or use other options such as http.Ok ...
	// return Response(400, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(401, HttpError{}) or use other options such as http.Ok ...
	// return Response(401, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(403, HttpError{}) or use other options such as http.Ok ...
	// return Response(403, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(404, HttpError{}) or use other options such as http.Ok ...
	// return Response(404, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(429, HttpError{}) or use other options such as http.Ok ...
	// return Response(429, HttpError{}), nil

	// TODO: Uncomment the next line to return response Response(500, HttpError{}) or use other options such as http.Ok ...
	// return Response(500, HttpError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateClearingandSettlement method not implemented")
}
