// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Billpaymandate - Reference to the applicable mandate for bill pay transactions
type Billpaymandate struct {

	// Identification of a bill pay mandate
	BillPayMandateIdentification string `json:"BillPayMandateIdentification,omitempty"`

	// Modaliteis of a bill pay mandate
	BillPayServiceConfiguration string `json:"BillPayServiceConfiguration,omitempty"`
}

// AssertBillpaymandateRequired checks if the required fields are not zero-ed
func AssertBillpaymandateRequired(obj Billpaymandate) error {
	return nil
}

// AssertBillpaymandateConstraints checks if the values respects the defined constraints
func AssertBillpaymandateConstraints(obj Billpaymandate) error {
	return nil
}
