// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Plantype - A Classification value that specifies the type of Plan
type Plantype struct {

	PlanTypeName Name `json:"PlanTypeName,omitempty"`

	PlanType Plantypevalues `json:"PlanType,omitempty"`
}

// AssertPlantypeRequired checks if the required fields are not zero-ed
func AssertPlantypeRequired(obj Plantype) error {
	if err := AssertNameRequired(obj.PlanTypeName); err != nil {
		return err
	}
	return nil
}

// AssertPlantypeConstraints checks if the values respects the defined constraints
func AssertPlantypeConstraints(obj Plantype) error {
	if err := AssertNameConstraints(obj.PlanTypeName); err != nil {
		return err
	}
	return nil
}
