// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Lientransaction - The collection of applicable rates
type Lientransaction struct {

	LienAmount Amount `json:"LienAmount,omitempty"`

	LienStartDate Datetime `json:"LienStartDate,omitempty"`

	LienExpiryDate Datetime `json:"LienExpiryDate,omitempty"`

	LienStatus Status `json:"LienStatus,omitempty"`
}

// AssertLientransactionRequired checks if the required fields are not zero-ed
func AssertLientransactionRequired(obj Lientransaction) error {
	if err := AssertAmountRequired(obj.LienAmount); err != nil {
		return err
	}
	if err := AssertDatetimeRequired(obj.LienStartDate); err != nil {
		return err
	}
	if err := AssertDatetimeRequired(obj.LienExpiryDate); err != nil {
		return err
	}
	if err := AssertStatusRequired(obj.LienStatus); err != nil {
		return err
	}
	return nil
}

// AssertLientransactionConstraints checks if the values respects the defined constraints
func AssertLientransactionConstraints(obj Lientransaction) error {
	if err := AssertAmountConstraints(obj.LienAmount); err != nil {
		return err
	}
	if err := AssertDatetimeConstraints(obj.LienStartDate); err != nil {
		return err
	}
	if err := AssertDatetimeConstraints(obj.LienExpiryDate); err != nil {
		return err
	}
	if err := AssertStatusConstraints(obj.LienStatus); err != nil {
		return err
	}
	return nil
}
