// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Arrangementlifecyclestatus - A characteristic of arrangement which refers to the LifecycleStatus of arrangement (e.g., requested, proposed, offered, accepted, cancelled, terminated, fulfilled, etc.)
type Arrangementlifecyclestatus struct {

	ArrangementLifecycleStatus Status `json:"ArrangementLifecycleStatus,omitempty"`

	ArrangementLifecycleStatusType Arrangementlifecyclestatustypevalues `json:"ArrangementLifecycleStatusType,omitempty"`
}

// AssertArrangementlifecyclestatusRequired checks if the required fields are not zero-ed
func AssertArrangementlifecyclestatusRequired(obj Arrangementlifecyclestatus) error {
	if err := AssertStatusRequired(obj.ArrangementLifecycleStatus); err != nil {
		return err
	}
	return nil
}

// AssertArrangementlifecyclestatusConstraints checks if the values respects the defined constraints
func AssertArrangementlifecyclestatusConstraints(obj Arrangementlifecyclestatus) error {
	if err := AssertStatusConstraints(obj.ArrangementLifecycleStatus); err != nil {
		return err
	}
	return nil
}
