// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Datetimeperiod - 
type Datetimeperiod struct {

	FromDateTime Datetime `json:"FromDateTime,omitempty"`

	ToDateTime Datetime `json:"ToDateTime,omitempty"`
}

// AssertDatetimeperiodRequired checks if the required fields are not zero-ed
func AssertDatetimeperiodRequired(obj Datetimeperiod) error {
	if err := AssertDatetimeRequired(obj.FromDateTime); err != nil {
		return err
	}
	if err := AssertDatetimeRequired(obj.ToDateTime); err != nil {
		return err
	}
	return nil
}

// AssertDatetimeperiodConstraints checks if the values respects the defined constraints
func AssertDatetimeperiodConstraints(obj Datetimeperiod) error {
	if err := AssertDatetimeConstraints(obj.FromDateTime); err != nil {
		return err
	}
	if err := AssertDatetimeConstraints(obj.ToDateTime); err != nil {
		return err
	}
	return nil
}
