// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Schedule - Timetable to fulfill Leasing Arrangement ||  |
type Schedule struct {

	// 
	ScheduleType string `json:"ScheduleType,omitempty"`
}

// AssertScheduleRequired checks if the required fields are not zero-ed
func AssertScheduleRequired(obj Schedule) error {
	return nil
}

// AssertScheduleConstraints checks if the values respects the defined constraints
func AssertScheduleConstraints(obj Schedule) error {
	return nil
}
