// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Party - 
type Party struct {

	PartyName Name `json:"PartyName,omitempty"`

	PartyType Partytypevalues `json:"PartyType,omitempty"`

	PartyDateTime Datetime `json:"PartyDateTime,omitempty"`

	PartyIdentification Partyidentification `json:"PartyIdentification,omitempty"`

	PartyLegalStructureType Partylegalstructuretypevalues `json:"PartyLegalStructureType,omitempty"`
}

// AssertPartyRequired checks if the required fields are not zero-ed
func AssertPartyRequired(obj Party) error {
	if err := AssertNameRequired(obj.PartyName); err != nil {
		return err
	}
	if err := AssertDatetimeRequired(obj.PartyDateTime); err != nil {
		return err
	}
	if err := AssertPartyidentificationRequired(obj.PartyIdentification); err != nil {
		return err
	}
	return nil
}

// AssertPartyConstraints checks if the values respects the defined constraints
func AssertPartyConstraints(obj Party) error {
	if err := AssertNameConstraints(obj.PartyName); err != nil {
		return err
	}
	if err := AssertDatetimeConstraints(obj.PartyDateTime); err != nil {
		return err
	}
	if err := AssertPartyidentificationConstraints(obj.PartyIdentification); err != nil {
		return err
	}
	return nil
}
