// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi


import (
	"fmt"
)


// Devicecustomizationtypevalues : >  * `CardDesign` -   
type Devicecustomizationtypevalues string

// List of Devicecustomizationtypevalues
const (
	CARD_DESIGN Devicecustomizationtypevalues = "CardDesign"
)

// AllowedDevicecustomizationtypevaluesEnumValues is all the allowed values of Devicecustomizationtypevalues enum
var AllowedDevicecustomizationtypevaluesEnumValues = []Devicecustomizationtypevalues{
	"CardDesign",
}

// validDevicecustomizationtypevaluesEnumValue provides a map of Devicecustomizationtypevaluess for fast verification of use input
var validDevicecustomizationtypevaluesEnumValues = map[Devicecustomizationtypevalues]struct{}{
	"CardDesign": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Devicecustomizationtypevalues) IsValid() bool {
	_, ok := validDevicecustomizationtypevaluesEnumValues[v]
	return ok
}

// NewDevicecustomizationtypevaluesFromValue returns a pointer to a valid Devicecustomizationtypevalues
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDevicecustomizationtypevaluesFromValue(v string) (Devicecustomizationtypevalues, error) {
	ev := Devicecustomizationtypevalues(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Devicecustomizationtypevalues: valid values are %v", v, AllowedDevicecustomizationtypevaluesEnumValues)
}



// AssertDevicecustomizationtypevaluesRequired checks if the required fields are not zero-ed
func AssertDevicecustomizationtypevaluesRequired(obj Devicecustomizationtypevalues) error {
	return nil
}

// AssertDevicecustomizationtypevaluesConstraints checks if the values respects the defined constraints
func AssertDevicecustomizationtypevaluesConstraints(obj Devicecustomizationtypevalues) error {
	return nil
}
