// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Involvedparty - Entity that assigns and manages the identification.
type Involvedparty struct {

	PartyReference Party `json:"PartyReference,omitempty"`

	PartyInvolvement Partyrole `json:"PartyInvolvement,omitempty"`
}

// AssertInvolvedpartyRequired checks if the required fields are not zero-ed
func AssertInvolvedpartyRequired(obj Involvedparty) error {
	if err := AssertPartyRequired(obj.PartyReference); err != nil {
		return err
	}
	if err := AssertPartyroleRequired(obj.PartyInvolvement); err != nil {
		return err
	}
	return nil
}

// AssertInvolvedpartyConstraints checks if the values respects the defined constraints
func AssertInvolvedpartyConstraints(obj Involvedparty) error {
	if err := AssertPartyConstraints(obj.PartyReference); err != nil {
		return err
	}
	if err := AssertPartyroleConstraints(obj.PartyInvolvement); err != nil {
		return err
	}
	return nil
}
