// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Accountcurrency - 
type Accountcurrency struct {

	AccountCurrencyType Currencytypevalues `json:"AccountCurrencyType,omitempty"`

	AccountCurrency Currencycode `json:"AccountCurrency,omitempty"`
}

// AssertAccountcurrencyRequired checks if the required fields are not zero-ed
func AssertAccountcurrencyRequired(obj Accountcurrency) error {
	if err := AssertCurrencycodeRequired(obj.AccountCurrency); err != nil {
		return err
	}
	return nil
}

// AssertAccountcurrencyConstraints checks if the values respects the defined constraints
func AssertAccountcurrencyConstraints(obj Accountcurrency) error {
	if err := AssertCurrencycodeConstraints(obj.AccountCurrency); err != nil {
		return err
	}
	return nil
}
