// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Financialfacility - The purpose or associated facility linked to the lien
type Financialfacility struct {

	// A production or operational capacity to perform a business function for delivering a banking product or service  A functional classification of banking product that provides ongoing capacity to deliver financial services (e.g. loan service, payment service)   
	FinancialFacility string `json:"FinancialFacility,omitempty"`
}

// AssertFinancialfacilityRequired checks if the required fields are not zero-ed
func AssertFinancialfacilityRequired(obj Financialfacility) error {
	return nil
}

// AssertFinancialfacilityConstraints checks if the values respects the defined constraints
func AssertFinancialfacilityConstraints(obj Financialfacility) error {
	return nil
}
