// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Datetime - 
type Datetime struct {

	// 
	DateTimeContent string `json:"DateTimeContent,omitempty"`

	// 
	TimeZoneCode string `json:"TimeZoneCode,omitempty"`

	// 
	DaylightSavingIndicator string `json:"DaylightSavingIndicator,omitempty"`
}

// AssertDatetimeRequired checks if the required fields are not zero-ed
func AssertDatetimeRequired(obj Datetime) error {
	return nil
}

// AssertDatetimeConstraints checks if the values respects the defined constraints
func AssertDatetimeConstraints(obj Datetime) error {
	return nil
}
