// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Accountstatus - A characteristic of account which refers to the LifecycleStatus of account like opened, closed, blocked, etc.  Specifies the current state of an account. (ISO20022)
type Accountstatus struct {

	AccountStatus Status `json:"AccountStatus,omitempty"`

	AccountStatusType Accountstatustypevalues `json:"AccountStatusType,omitempty"`
}

// AssertAccountstatusRequired checks if the required fields are not zero-ed
func AssertAccountstatusRequired(obj Accountstatus) error {
	if err := AssertStatusRequired(obj.AccountStatus); err != nil {
		return err
	}
	return nil
}

// AssertAccountstatusConstraints checks if the values respects the defined constraints
func AssertAccountstatusConstraints(obj Accountstatus) error {
	if err := AssertStatusConstraints(obj.AccountStatus); err != nil {
		return err
	}
	return nil
}
