// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Condition - Term and condition to govern the use of loan product and the loan agreement in general.
type Condition struct {

	// Condition is a premise upon which the fulfillment of an agreement depends   General and special arrangements, provisions, requirements, rules, specifications, and standards that form an integral part of an agreement or contract.  Read more: http://www.businessdictionary.com/definition/terms-and-conditions.html  
	Condition string `json:"Condition,omitempty"`
}

// AssertConditionRequired checks if the required fields are not zero-ed
func AssertConditionRequired(obj Condition) error {
	return nil
}

// AssertConditionConstraints checks if the values respects the defined constraints
func AssertConditionConstraints(obj Condition) error {
	return nil
}
