// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Paymenttransactionstatus - Specifies the status of a payment transaction at a specified time. Elements
type Paymenttransactionstatus struct {

	PaymentTransactionStatus Status `json:"PaymentTransactionStatus,omitempty"`

	PaymentTransactionStatusType Paymenttransactionstatustypevalues `json:"PaymentTransactionStatusType,omitempty"`
}

// AssertPaymenttransactionstatusRequired checks if the required fields are not zero-ed
func AssertPaymenttransactionstatusRequired(obj Paymenttransactionstatus) error {
	if err := AssertStatusRequired(obj.PaymentTransactionStatus); err != nil {
		return err
	}
	return nil
}

// AssertPaymenttransactionstatusConstraints checks if the values respects the defined constraints
func AssertPaymenttransactionstatusConstraints(obj Paymenttransactionstatus) error {
	if err := AssertStatusConstraints(obj.PaymentTransactionStatus); err != nil {
		return err
	}
	return nil
}
