// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Yesnoindicator - Indicates wether a pre-notification must be sent by the creditor to the debtor before a direct debit occurs (ISO20022)
type Yesnoindicator struct {

	// Indicates a \"Yes\" or \"No\" type of answer for an element. (ISO20022) true: Yes false: No
	Yesnoindicator string `json:"Yesnoindicator,omitempty"`
}

// AssertYesnoindicatorRequired checks if the required fields are not zero-ed
func AssertYesnoindicatorRequired(obj Yesnoindicator) error {
	return nil
}

// AssertYesnoindicatorConstraints checks if the values respects the defined constraints
func AssertYesnoindicatorConstraints(obj Yesnoindicator) error {
	return nil
}
