// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi


import (
	"fmt"
)


// Feeapplicationfrequencyvalues : >  * `Onclosing` - This fee is triggered on closing of a product  * `Onopening` - This fee is triggered on opening of a product  * `Chargingperiod` - This fee is triggered at the end of each charging period  * `Daily` - This fee is triggered every day  * `Peritem` - This fee is triggered by the processing of an item on the product  * `Monthly` - This fee is triggered monthly  * `Onanniversary` - This fee is triggered on the anniversary of opening the product  * `Other` - Other Fee Frequency  * `Perhundredpounds` - This fee is triggered for every hundred pounds withdrawn  * `Perhour` - This fee is triggered every hour  * `Peroccurrence` - This fee is triggered per occurrence of the transaction or service. This differs from PerItem, in that if a batch of items is processed at the same time, a PerOccurrence fee would incur a single charge, whereas a PerItem fee would be charged for each item within the batch.  * `Persheet` - This fee is levied on every statement sheet  * `Pertransaction` - The fee is charged for each transaction  * `Pertransactionamount` - The amount stated is levied for each transaction processed  * `Pertransactionpercentage` - The fee amount is the given percentage of the transaction processed and is levied for each transaction  * `Quarterly` - This fee is triggered at the end of every quarter  * `Sixmonthly` - This fee is triggered at the end of every 6 month period  * `Statementmonthly` - This fee is triggered based on a monthly statement period  * `Weekly` - The fee is triggered weekly  * `Yearly` - This fee is triggered yearly  
type Feeapplicationfrequencyvalues string

// List of Feeapplicationfrequencyvalues
const (
	ONCLOSING Feeapplicationfrequencyvalues = "Onclosing"
	ONOPENING Feeapplicationfrequencyvalues = "Onopening"
	CHARGINGPERIOD Feeapplicationfrequencyvalues = "Chargingperiod"
	DAILY Feeapplicationfrequencyvalues = "Daily"
	PERITEM Feeapplicationfrequencyvalues = "Peritem"
	MONTHLY Feeapplicationfrequencyvalues = "Monthly"
	ONANNIVERSARY Feeapplicationfrequencyvalues = "Onanniversary"
	OTHER Feeapplicationfrequencyvalues = "Other"
	PERHUNDREDPOUNDS Feeapplicationfrequencyvalues = "Perhundredpounds"
	PERHOUR Feeapplicationfrequencyvalues = "Perhour"
	PEROCCURRENCE Feeapplicationfrequencyvalues = "Peroccurrence"
	PERSHEET Feeapplicationfrequencyvalues = "Persheet"
	PERTRANSACTION Feeapplicationfrequencyvalues = "Pertransaction"
	PERTRANSACTIONAMOUNT Feeapplicationfrequencyvalues = "Pertransactionamount"
	PERTRANSACTIONPERCENTAGE Feeapplicationfrequencyvalues = "Pertransactionpercentage"
	QUARTERLY Feeapplicationfrequencyvalues = "Quarterly"
	SIXMONTHLY Feeapplicationfrequencyvalues = "Sixmonthly"
	STATEMENTMONTHLY Feeapplicationfrequencyvalues = "Statementmonthly"
	WEEKLY Feeapplicationfrequencyvalues = "Weekly"
	YEARLY Feeapplicationfrequencyvalues = "Yearly"
)

// AllowedFeeapplicationfrequencyvaluesEnumValues is all the allowed values of Feeapplicationfrequencyvalues enum
var AllowedFeeapplicationfrequencyvaluesEnumValues = []Feeapplicationfrequencyvalues{
	"Onclosing",
	"Onopening",
	"Chargingperiod",
	"Daily",
	"Peritem",
	"Monthly",
	"Onanniversary",
	"Other",
	"Perhundredpounds",
	"Perhour",
	"Peroccurrence",
	"Persheet",
	"Pertransaction",
	"Pertransactionamount",
	"Pertransactionpercentage",
	"Quarterly",
	"Sixmonthly",
	"Statementmonthly",
	"Weekly",
	"Yearly",
}

// validFeeapplicationfrequencyvaluesEnumValue provides a map of Feeapplicationfrequencyvaluess for fast verification of use input
var validFeeapplicationfrequencyvaluesEnumValues = map[Feeapplicationfrequencyvalues]struct{}{
	"Onclosing": {},
	"Onopening": {},
	"Chargingperiod": {},
	"Daily": {},
	"Peritem": {},
	"Monthly": {},
	"Onanniversary": {},
	"Other": {},
	"Perhundredpounds": {},
	"Perhour": {},
	"Peroccurrence": {},
	"Persheet": {},
	"Pertransaction": {},
	"Pertransactionamount": {},
	"Pertransactionpercentage": {},
	"Quarterly": {},
	"Sixmonthly": {},
	"Statementmonthly": {},
	"Weekly": {},
	"Yearly": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Feeapplicationfrequencyvalues) IsValid() bool {
	_, ok := validFeeapplicationfrequencyvaluesEnumValues[v]
	return ok
}

// NewFeeapplicationfrequencyvaluesFromValue returns a pointer to a valid Feeapplicationfrequencyvalues
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFeeapplicationfrequencyvaluesFromValue(v string) (Feeapplicationfrequencyvalues, error) {
	ev := Feeapplicationfrequencyvalues(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Feeapplicationfrequencyvalues: valid values are %v", v, AllowedFeeapplicationfrequencyvaluesEnumValues)
}



// AssertFeeapplicationfrequencyvaluesRequired checks if the required fields are not zero-ed
func AssertFeeapplicationfrequencyvaluesRequired(obj Feeapplicationfrequencyvalues) error {
	return nil
}

// AssertFeeapplicationfrequencyvaluesConstraints checks if the values respects the defined constraints
func AssertFeeapplicationfrequencyvaluesConstraints(obj Feeapplicationfrequencyvalues) error {
	return nil
}
