// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Status - The status of Leasing Arrangement Status |Status  (https://www.iso20022.org/standardsrepository/type/Status)|Standard|ISO20022 BM ()
type Status struct {

	StatusReason Text `json:"StatusReason,omitempty"`

	StatusDateTime Datetime `json:"StatusDateTime,omitempty"`

	StatusValidityPeriod Datetimeperiod `json:"StatusValidityPeriod,omitempty"`

	StatusInvolvedParty Involvedparty `json:"StatusInvolvedParty,omitempty"`
}

// AssertStatusRequired checks if the required fields are not zero-ed
func AssertStatusRequired(obj Status) error {
	if err := AssertTextRequired(obj.StatusReason); err != nil {
		return err
	}
	if err := AssertDatetimeRequired(obj.StatusDateTime); err != nil {
		return err
	}
	if err := AssertDatetimeperiodRequired(obj.StatusValidityPeriod); err != nil {
		return err
	}
	if err := AssertInvolvedpartyRequired(obj.StatusInvolvedParty); err != nil {
		return err
	}
	return nil
}

// AssertStatusConstraints checks if the values respects the defined constraints
func AssertStatusConstraints(obj Status) error {
	if err := AssertTextConstraints(obj.StatusReason); err != nil {
		return err
	}
	if err := AssertDatetimeConstraints(obj.StatusDateTime); err != nil {
		return err
	}
	if err := AssertDatetimeperiodConstraints(obj.StatusValidityPeriod); err != nil {
		return err
	}
	if err := AssertInvolvedpartyConstraints(obj.StatusInvolvedParty); err != nil {
		return err
	}
	return nil
}
