// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Address - 
type Address struct {

	AddressType Addresstypevalues `json:"AddressType,omitempty"`

	LocationReference Location `json:"LocationReference,omitempty"`
}

// AssertAddressRequired checks if the required fields are not zero-ed
func AssertAddressRequired(obj Address) error {
	if err := AssertLocationRequired(obj.LocationReference); err != nil {
		return err
	}
	return nil
}

// AssertAddressConstraints checks if the values respects the defined constraints
func AssertAddressConstraints(obj Address) error {
	if err := AssertLocationConstraints(obj.LocationReference); err != nil {
		return err
	}
	return nil
}
