// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Directdebitmandate - Reference to the applicable mandate for direct debits
type Directdebitmandate struct {

	DirectDebitMandateIdentification Identifier `json:"DirectDebitMandateIdentification,omitempty"`

	DirectDebitPurpose Text `json:"DirectDebitPurpose,omitempty"`

	DirectDebitSourceAccount Account `json:"DirectDebitSourceAccount,omitempty"`

	DirectDebitStatus Directdebitstatusvalues `json:"DirectDebitStatus,omitempty"`

	DirectDebitType Directdebittypevalues `json:"DirectDebitType,omitempty"`
}

// AssertDirectdebitmandateRequired checks if the required fields are not zero-ed
func AssertDirectdebitmandateRequired(obj Directdebitmandate) error {
	if err := AssertIdentifierRequired(obj.DirectDebitMandateIdentification); err != nil {
		return err
	}
	if err := AssertTextRequired(obj.DirectDebitPurpose); err != nil {
		return err
	}
	if err := AssertAccountRequired(obj.DirectDebitSourceAccount); err != nil {
		return err
	}
	return nil
}

// AssertDirectdebitmandateConstraints checks if the values respects the defined constraints
func AssertDirectdebitmandateConstraints(obj Directdebitmandate) error {
	if err := AssertIdentifierConstraints(obj.DirectDebitMandateIdentification); err != nil {
		return err
	}
	if err := AssertTextConstraints(obj.DirectDebitPurpose); err != nil {
		return err
	}
	if err := AssertAccountConstraints(obj.DirectDebitSourceAccount); err != nil {
		return err
	}
	return nil
}
