// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Accountbalance - The state of the obligations managed on the account, the result of all entries on the account.  Numerical representation of the net increases and decreases in an account at a specific point in time. (ISO20022)  Banking: Amount available in an account for withdrawal or use. Read more: http://www.businessdictionary.com/definition/balance.html  Bookkeeping: Difference between the debit and credit sides of an account. Read more: http://www.businessdictionary.com/definition/balance.html
type Accountbalance struct {

	BalanceAmount Amount `json:"BalanceAmount,omitempty"`

	BalanceType Balancetypevalues `json:"BalanceType,omitempty"`

	BalanceDate Datetime `json:"BalanceDate,omitempty"`

	BalanceIndicator Debitcreditindicatortvalues `json:"BalanceIndicator,omitempty"`
}

// AssertAccountbalanceRequired checks if the required fields are not zero-ed
func AssertAccountbalanceRequired(obj Accountbalance) error {
	if err := AssertAmountRequired(obj.BalanceAmount); err != nil {
		return err
	}
	if err := AssertDatetimeRequired(obj.BalanceDate); err != nil {
		return err
	}
	return nil
}

// AssertAccountbalanceConstraints checks if the values respects the defined constraints
func AssertAccountbalanceConstraints(obj Accountbalance) error {
	if err := AssertAmountConstraints(obj.BalanceAmount); err != nil {
		return err
	}
	if err := AssertDatetimeConstraints(obj.BalanceDate); err != nil {
		return err
	}
	return nil
}
