// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// HttpError - Status Attributes
type HttpError struct {

	StatusCode string `json:"status_code,omitempty"`

	Status string `json:"status,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertHttpErrorRequired checks if the required fields are not zero-ed
func AssertHttpErrorRequired(obj HttpError) error {
	return nil
}

// AssertHttpErrorConstraints checks if the values respects the defined constraints
func AssertHttpErrorConstraints(obj HttpError) error {
	return nil
}
