// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Budgettype - A Classification value that specifies the type of Budget
type Budgettype struct {

	BudgetTypeName Name `json:"BudgetTypeName,omitempty"`

	BudgetType Budgettypevalues `json:"BudgetType,omitempty"`
}

// AssertBudgettypeRequired checks if the required fields are not zero-ed
func AssertBudgettypeRequired(obj Budgettype) error {
	if err := AssertNameRequired(obj.BudgetTypeName); err != nil {
		return err
	}
	return nil
}

// AssertBudgettypeConstraints checks if the values respects the defined constraints
func AssertBudgettypeConstraints(obj Budgettype) error {
	if err := AssertNameConstraints(obj.BudgetTypeName); err != nil {
		return err
	}
	return nil
}
