// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Rate - Rate used for calculation of the tax.
type Rate struct {

	RateValue Value `json:"RateValue,omitempty"`

	RateUnit Text `json:"RateUnit,omitempty"`

	RatePeriod Datetimeperiod `json:"RatePeriod,omitempty"`

	RateCapitalUnit Text `json:"RateCapitalUnit,omitempty"`
}

// AssertRateRequired checks if the required fields are not zero-ed
func AssertRateRequired(obj Rate) error {
	if err := AssertValueRequired(obj.RateValue); err != nil {
		return err
	}
	if err := AssertTextRequired(obj.RateUnit); err != nil {
		return err
	}
	if err := AssertDatetimeperiodRequired(obj.RatePeriod); err != nil {
		return err
	}
	if err := AssertTextRequired(obj.RateCapitalUnit); err != nil {
		return err
	}
	return nil
}

// AssertRateConstraints checks if the values respects the defined constraints
func AssertRateConstraints(obj Rate) error {
	if err := AssertValueConstraints(obj.RateValue); err != nil {
		return err
	}
	if err := AssertTextConstraints(obj.RateUnit); err != nil {
		return err
	}
	if err := AssertDatetimeperiodConstraints(obj.RatePeriod); err != nil {
		return err
	}
	if err := AssertTextConstraints(obj.RateCapitalUnit); err != nil {
		return err
	}
	return nil
}
