// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Settlementtransaction - A record of a settlement transaction
type Settlementtransaction struct {

	// Transaction that is the result of fulfilling a settlement arrangement
	SettlementTransaction string `json:"SettlementTransaction,omitempty"`
}

// AssertSettlementtransactionRequired checks if the required fields are not zero-ed
func AssertSettlementtransactionRequired(obj Settlementtransaction) error {
	return nil
}

// AssertSettlementtransactionConstraints checks if the values respects the defined constraints
func AssertSettlementtransactionConstraints(obj Settlementtransaction) error {
	return nil
}
