// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi


import (
	"fmt"
)


// Modalitytypevalues : >  * `AllocationModality` -   * `CalculationModality` -   * `DerivationModality` -   * `PaymentModality` -   * `ProcessingModality` -   * `ApplicationModality` -   * `DeliveryModality` -   
type Modalitytypevalues string

// List of Modalitytypevalues
const (
	ALLOCATION_MODALITY Modalitytypevalues = "AllocationModality"
	CALCULATION_MODALITY Modalitytypevalues = "CalculationModality"
	DERIVATION_MODALITY Modalitytypevalues = "DerivationModality"
	PAYMENT_MODALITY Modalitytypevalues = "PaymentModality"
	PROCESSING_MODALITY Modalitytypevalues = "ProcessingModality"
	APPLICATION_MODALITY Modalitytypevalues = "ApplicationModality"
	DELIVERY_MODALITY Modalitytypevalues = "DeliveryModality"
)

// AllowedModalitytypevaluesEnumValues is all the allowed values of Modalitytypevalues enum
var AllowedModalitytypevaluesEnumValues = []Modalitytypevalues{
	"AllocationModality",
	"CalculationModality",
	"DerivationModality",
	"PaymentModality",
	"ProcessingModality",
	"ApplicationModality",
	"DeliveryModality",
}

// validModalitytypevaluesEnumValue provides a map of Modalitytypevaluess for fast verification of use input
var validModalitytypevaluesEnumValues = map[Modalitytypevalues]struct{}{
	"AllocationModality": {},
	"CalculationModality": {},
	"DerivationModality": {},
	"PaymentModality": {},
	"ProcessingModality": {},
	"ApplicationModality": {},
	"DeliveryModality": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Modalitytypevalues) IsValid() bool {
	_, ok := validModalitytypevaluesEnumValues[v]
	return ok
}

// NewModalitytypevaluesFromValue returns a pointer to a valid Modalitytypevalues
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModalitytypevaluesFromValue(v string) (Modalitytypevalues, error) {
	ev := Modalitytypevalues(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Modalitytypevalues: valid values are %v", v, AllowedModalitytypevaluesEnumValues)
}



// AssertModalitytypevaluesRequired checks if the required fields are not zero-ed
func AssertModalitytypevaluesRequired(obj Modalitytypevalues) error {
	return nil
}

// AssertModalitytypevaluesConstraints checks if the values respects the defined constraints
func AssertModalitytypevaluesConstraints(obj Modalitytypevalues) error {
	return nil
}
