// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Partyrole - 
type Partyrole struct {

	PartyRoleType Text `json:"PartyRoleType,omitempty"`

	PartyRoleName Name `json:"PartyRoleName,omitempty"`

	PartyRoleValidityPeriod Datetimeperiod `json:"PartyRoleValidityPeriod,omitempty"`

	PartyInvolvementType Partyinvolvementtypevalues `json:"PartyInvolvementType,omitempty"`
}

// AssertPartyroleRequired checks if the required fields are not zero-ed
func AssertPartyroleRequired(obj Partyrole) error {
	if err := AssertTextRequired(obj.PartyRoleType); err != nil {
		return err
	}
	if err := AssertNameRequired(obj.PartyRoleName); err != nil {
		return err
	}
	if err := AssertDatetimeperiodRequired(obj.PartyRoleValidityPeriod); err != nil {
		return err
	}
	return nil
}

// AssertPartyroleConstraints checks if the values respects the defined constraints
func AssertPartyroleConstraints(obj Partyrole) error {
	if err := AssertTextConstraints(obj.PartyRoleType); err != nil {
		return err
	}
	if err := AssertNameConstraints(obj.PartyRoleName); err != nil {
		return err
	}
	if err := AssertDatetimeperiodConstraints(obj.PartyRoleValidityPeriod); err != nil {
		return err
	}
	return nil
}
