// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Country - Country of the location.
type Country struct {

	NationalRegulatoryAuthority Involvedparty `json:"NationalRegulatoryAuthority,omitempty"`
}

// AssertCountryRequired checks if the required fields are not zero-ed
func AssertCountryRequired(obj Country) error {
	if err := AssertInvolvedpartyRequired(obj.NationalRegulatoryAuthority); err != nil {
		return err
	}
	return nil
}

// AssertCountryConstraints checks if the values respects the defined constraints
func AssertCountryConstraints(obj Country) error {
	if err := AssertInvolvedpartyConstraints(obj.NationalRegulatoryAuthority); err != nil {
		return err
	}
	return nil
}
