// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Date - The date and time the deposit was initiated
type Date struct {

	// 
	DateContent string `json:"DateContent,omitempty"`
}

// AssertDateRequired checks if the required fields are not zero-ed
func AssertDateRequired(obj Date) error {
	return nil
}

// AssertDateConstraints checks if the values respects the defined constraints
func AssertDateConstraints(obj Date) error {
	return nil
}
