// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Value - 
type Value struct {

	// Data or set of data   - A value is the concept of worth in general that is assigned or is determined by measurement, assessment or calculation. (UN/CEFACT)
	Value string `json:"Value,omitempty"`
}

// AssertValueRequired checks if the required fields are not zero-ed
func AssertValueRequired(obj Value) error {
	return nil
}

// AssertValueConstraints checks if the values respects the defined constraints
func AssertValueConstraints(obj Value) error {
	return nil
}
