// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Currencycode - The curreny which is arranged in Leasing Arrangement CurrencyCode|CurrencyCode (https://www.iso20022.org/standardsrepository/type/CurrencyCode)|Standard|ISO20022 BM ()
type Currencycode struct {

	// A code identifying a currency according to ISO-4217. A currency is a system of money in general use in a particular country.  Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 \"Codes for the representation of currencies and funds\". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters. (ISO20022)  
	Currencycode string `json:"Currencycode,omitempty"`
}

// AssertCurrencycodeRequired checks if the required fields are not zero-ed
func AssertCurrencycodeRequired(obj Currencycode) error {
	return nil
}

// AssertCurrencycodeConstraints checks if the values respects the defined constraints
func AssertCurrencycodeConstraints(obj Currencycode) error {
	return nil
}
