// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Name - The name of the product used for marketing purposes from a customer perspective. I.e. what the customer would recognise. (OB) Name|Name (https://www.iso20022.org/standardsrepository/type/Name)|Standard|ISO20022 ()
type Name struct {

	// A name is a word or phrase that constitutes the distinctive designation of a person, place, thing or concept. (UN/CEFAT)
	Name string `json:"Name,omitempty"`
}

// AssertNameRequired checks if the required fields are not zero-ed
func AssertNameRequired(obj Name) error {
	return nil
}

// AssertNameConstraints checks if the values respects the defined constraints
func AssertNameConstraints(obj Name) error {
	return nil
}
