// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Accounttype - Specifies the category of account like payment account, loan account, cash account, securities account, etc. 
type Accounttype struct {

	AccountType Accounttypevalues `json:"AccountType,omitempty"`

	AccountTypeName Name `json:"AccountTypeName,omitempty"`
}

// AssertAccounttypeRequired checks if the required fields are not zero-ed
func AssertAccounttypeRequired(obj Accounttype) error {
	if err := AssertNameRequired(obj.AccountTypeName); err != nil {
		return err
	}
	return nil
}

// AssertAccounttypeConstraints checks if the values respects the defined constraints
func AssertAccounttypeConstraints(obj Accounttype) error {
	if err := AssertNameConstraints(obj.AccountTypeName); err != nil {
		return err
	}
	return nil
}
