// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Jurisdiction - Reference to the jurisdiction that is assigned to Leasing Arrangement in case of legal dispute. Jurisdiction|Jurisdiction (https://www.iso20022.org/standardsrepository/type/Jurisdiction)|Standard|ISO20022 BM ()
type Jurisdiction struct {

	// Jurisdiction that will be assigned in case of legal dispute.
	Jurisdiction string `json:"Jurisdiction,omitempty"`
}

// AssertJurisdictionRequired checks if the required fields are not zero-ed
func AssertJurisdictionRequired(obj Jurisdiction) error {
	return nil
}

// AssertJurisdictionConstraints checks if the values respects the defined constraints
func AssertJurisdictionConstraints(obj Jurisdiction) error {
	return nil
}
