// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// LeasingOutcome - The product features/services available with a financical facility
type LeasingOutcome struct {

	LeasingFinancialFacility Loanagreement `json:"LeasingFinancialFacility,omitempty"`

	LeasingWorkProduct Workproduct `json:"LeasingWorkProduct,omitempty"`
}

// AssertLeasingOutcomeRequired checks if the required fields are not zero-ed
func AssertLeasingOutcomeRequired(obj LeasingOutcome) error {
	if err := AssertLoanagreementRequired(obj.LeasingFinancialFacility); err != nil {
		return err
	}
	if err := AssertWorkproductRequired(obj.LeasingWorkProduct); err != nil {
		return err
	}
	return nil
}

// AssertLeasingOutcomeConstraints checks if the values respects the defined constraints
func AssertLeasingOutcomeConstraints(obj LeasingOutcome) error {
	if err := AssertLoanagreementConstraints(obj.LeasingFinancialFacility); err != nil {
		return err
	}
	if err := AssertWorkproductConstraints(obj.LeasingWorkProduct); err != nil {
		return err
	}
	return nil
}
