// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Lienarrangementmodality - The processing option applied to the lien
type Lienarrangementmodality struct {

	LienArrangementModalityType Modalitytypevalues `json:"LienArrangementModalityType,omitempty"`

	LienArrangementModalityParameter Feature `json:"LienArrangementModalityParameter,omitempty"`

	LienArrangementModalityGuideline Ruleset `json:"LienArrangementModalityGuideline,omitempty"`

	LienArrangementModalitySchedule Schedule `json:"LienArrangementModalitySchedule,omitempty"`
}

// AssertLienarrangementmodalityRequired checks if the required fields are not zero-ed
func AssertLienarrangementmodalityRequired(obj Lienarrangementmodality) error {
	if err := AssertFeatureRequired(obj.LienArrangementModalityParameter); err != nil {
		return err
	}
	if err := AssertRulesetRequired(obj.LienArrangementModalityGuideline); err != nil {
		return err
	}
	if err := AssertScheduleRequired(obj.LienArrangementModalitySchedule); err != nil {
		return err
	}
	return nil
}

// AssertLienarrangementmodalityConstraints checks if the values respects the defined constraints
func AssertLienarrangementmodalityConstraints(obj Lienarrangementmodality) error {
	if err := AssertFeatureConstraints(obj.LienArrangementModalityParameter); err != nil {
		return err
	}
	if err := AssertRulesetConstraints(obj.LienArrangementModalityGuideline); err != nil {
		return err
	}
	if err := AssertScheduleConstraints(obj.LienArrangementModalitySchedule); err != nil {
		return err
	}
	return nil
}
