// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Plannedaction - An action that is arranged in a plan for doing or achieving something 
type Plannedaction struct {

	// An action that is arranged in a plan for doing or achieving something 
	PlannedAction string `json:"PlannedAction,omitempty"`
}

// AssertPlannedactionRequired checks if the required fields are not zero-ed
func AssertPlannedactionRequired(obj Plannedaction) error {
	return nil
}

// AssertPlannedactionConstraints checks if the values respects the defined constraints
func AssertPlannedactionConstraints(obj Plannedaction) error {
	return nil
}
