// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Clearingsystemtypevalues - Specifies the system which plays a role in the clearing process. (ISO20022) Specifies the system which plays a role in the clearing of securities or cash. (ISO20022)
type Clearingsystemtypevalues struct {

	// Type of the system which plays a role in the clearing process.
	Clearingsystemtypevalues string `json:"Clearingsystemtypevalues,omitempty"`
}

// AssertClearingsystemtypevaluesRequired checks if the required fields are not zero-ed
func AssertClearingsystemtypevaluesRequired(obj Clearingsystemtypevalues) error {
	return nil
}

// AssertClearingsystemtypevaluesConstraints checks if the values respects the defined constraints
func AssertClearingsystemtypevaluesConstraints(obj Clearingsystemtypevalues) error {
	return nil
}
