// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi


import (
	"fmt"
)


// Partytypevalues : >  * `Person` - Human entity, as distinguished from a corporate entity (which is sometimes referred to as an 'artificial person'). ISO20022  * `Organisation` - Organised structure that is set up for a particular purpose. For example, a business, government body, department, charity, or financial institution. ISO20022  
type Partytypevalues string

// List of Partytypevalues
const (
	PERSON Partytypevalues = "Person"
	ORGANISATION Partytypevalues = "Organisation"
)

// AllowedPartytypevaluesEnumValues is all the allowed values of Partytypevalues enum
var AllowedPartytypevaluesEnumValues = []Partytypevalues{
	"Person",
	"Organisation",
}

// validPartytypevaluesEnumValue provides a map of Partytypevaluess for fast verification of use input
var validPartytypevaluesEnumValues = map[Partytypevalues]struct{}{
	"Person": {},
	"Organisation": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Partytypevalues) IsValid() bool {
	_, ok := validPartytypevaluesEnumValues[v]
	return ok
}

// NewPartytypevaluesFromValue returns a pointer to a valid Partytypevalues
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPartytypevaluesFromValue(v string) (Partytypevalues, error) {
	ev := Partytypevalues(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for Partytypevalues: valid values are %v", v, AllowedPartytypevaluesEnumValues)
}



// AssertPartytypevaluesRequired checks if the required fields are not zero-ed
func AssertPartytypevaluesRequired(obj Partytypevalues) error {
	return nil
}

// AssertPartytypevaluesConstraints checks if the values respects the defined constraints
func AssertPartytypevaluesConstraints(obj Partytypevalues) error {
	return nil
}
