// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Amount - Amount of money moved between the instructing agent and the instructed agent. (ISO20022)
type Amount struct {

	AmountValue Value `json:"AmountValue,omitempty"`

	AmountCurrency Currencycode `json:"AmountCurrency,omitempty"`

	// Decimal point position starts calulating from the right 
	DecimalPointPosition string `json:"DecimalPointPosition,omitempty"`

	AmountType Amounttypevalues `json:"AmountType,omitempty"`
}

// AssertAmountRequired checks if the required fields are not zero-ed
func AssertAmountRequired(obj Amount) error {
	if err := AssertValueRequired(obj.AmountValue); err != nil {
		return err
	}
	if err := AssertCurrencycodeRequired(obj.AmountCurrency); err != nil {
		return err
	}
	return nil
}

// AssertAmountConstraints checks if the values respects the defined constraints
func AssertAmountConstraints(obj Amount) error {
	if err := AssertValueConstraints(obj.AmountValue); err != nil {
		return err
	}
	if err := AssertCurrencycodeConstraints(obj.AmountCurrency); err != nil {
		return err
	}
	return nil
}
