// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Interesttransaction - A record of applied interest
type Interesttransaction struct {

	InterestTransactionAmount Amount `json:"InterestTransactionAmount,omitempty"`

	InterestTransactionDescription Text `json:"InterestTransactionDescription,omitempty"`

	InterestTransactionType Interesttransactiontypevalues `json:"InterestTransactionType,omitempty"`

	AppliedInterestRate Rate `json:"AppliedInterestRate,omitempty"`

	AppliedInteretType Interesttypevalues `json:"AppliedInteretType,omitempty"`

	InterestCreditDebitIndicator Debitcreditindicatortvalues `json:"InterestCreditDebitIndicator,omitempty"`
}

// AssertInteresttransactionRequired checks if the required fields are not zero-ed
func AssertInteresttransactionRequired(obj Interesttransaction) error {
	if err := AssertAmountRequired(obj.InterestTransactionAmount); err != nil {
		return err
	}
	if err := AssertTextRequired(obj.InterestTransactionDescription); err != nil {
		return err
	}
	if err := AssertRateRequired(obj.AppliedInterestRate); err != nil {
		return err
	}
	return nil
}

// AssertInteresttransactionConstraints checks if the values respects the defined constraints
func AssertInteresttransactionConstraints(obj Interesttransaction) error {
	if err := AssertAmountConstraints(obj.InterestTransactionAmount); err != nil {
		return err
	}
	if err := AssertTextConstraints(obj.InterestTransactionDescription); err != nil {
		return err
	}
	if err := AssertRateConstraints(obj.AppliedInterestRate); err != nil {
		return err
	}
	return nil
}
