// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Businessservicetypevalues - 
type Businessservicetypevalues struct {

	// 
	Businessservicetypevalues string `json:"Businessservicetypevalues,omitempty"`
}

// AssertBusinessservicetypevaluesRequired checks if the required fields are not zero-ed
func AssertBusinessservicetypevaluesRequired(obj Businessservicetypevalues) error {
	return nil
}

// AssertBusinessservicetypevaluesConstraints checks if the values respects the defined constraints
func AssertBusinessservicetypevaluesConstraints(obj Businessservicetypevalues) error {
	return nil
}
