// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Leasearrangement - Reference to Leasing Arrangement ||  |
type Leasearrangement struct {

	// 3585f822-574e-ea11-8289-069813aed0a6
	LeasingArrangementType string `json:"LeasingArrangementType,omitempty"`
}

// AssertLeasearrangementRequired checks if the required fields are not zero-ed
func AssertLeasearrangementRequired(obj Leasearrangement) error {
	return nil
}

// AssertLeasearrangementConstraints checks if the values respects the defined constraints
func AssertLeasearrangementConstraints(obj Leasearrangement) error {
	return nil
}
