// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Loanagreement - 
type Loanagreement struct {

	LoanTermAndCondition Condition `json:"LoanTermAndCondition,omitempty"`
}

// AssertLoanagreementRequired checks if the required fields are not zero-ed
func AssertLoanagreementRequired(obj Loanagreement) error {
	if err := AssertConditionRequired(obj.LoanTermAndCondition); err != nil {
		return err
	}
	return nil
}

// AssertLoanagreementConstraints checks if the values respects the defined constraints
func AssertLoanagreementConstraints(obj Loanagreement) error {
	if err := AssertConditionConstraints(obj.LoanTermAndCondition); err != nil {
		return err
	}
	return nil
}
