// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Budgetarrangement - An arrangement which is specifying an estimate of costs, revenues, and resources over a specified period, reflecting a reading of future financial conditions and goals. (adapted from Business Dictionary)
type Budgetarrangement struct {

	BudgetType Budgettype `json:"BudgetType,omitempty"`

	BudgetAmount Amount `json:"BudgetAmount,omitempty"`
}

// AssertBudgetarrangementRequired checks if the required fields are not zero-ed
func AssertBudgetarrangementRequired(obj Budgetarrangement) error {
	if err := AssertBudgettypeRequired(obj.BudgetType); err != nil {
		return err
	}
	if err := AssertAmountRequired(obj.BudgetAmount); err != nil {
		return err
	}
	return nil
}

// AssertBudgetarrangementConstraints checks if the values respects the defined constraints
func AssertBudgetarrangementConstraints(obj Budgetarrangement) error {
	if err := AssertBudgettypeConstraints(obj.BudgetType); err != nil {
		return err
	}
	if err := AssertAmountConstraints(obj.BudgetAmount); err != nil {
		return err
	}
	return nil
}
