// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Clearinginstruction - Customer specific default clearing instructions
type Clearinginstruction struct {

	// A request to do the clearing of transaction. 
	ClearingInstruction string `json:"ClearingInstruction,omitempty"`
}

// AssertClearinginstructionRequired checks if the required fields are not zero-ed
func AssertClearinginstructionRequired(obj Clearinginstruction) error {
	return nil
}

// AssertClearinginstructionConstraints checks if the values respects the defined constraints
func AssertClearinginstructionConstraints(obj Clearinginstruction) error {
	return nil
}
