// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Clearingarrangement - The clearing arrangement between the bank and clearing house - includes schedule, limits
type Clearingarrangement struct {

	ClearingSystem Clearingsystemtypevalues `json:"ClearingSystem,omitempty"`
}

// AssertClearingarrangementRequired checks if the required fields are not zero-ed
func AssertClearingarrangementRequired(obj Clearingarrangement) error {
	if err := AssertClearingsystemtypevaluesRequired(obj.ClearingSystem); err != nil {
		return err
	}
	return nil
}

// AssertClearingarrangementConstraints checks if the values respects the defined constraints
func AssertClearingarrangementConstraints(obj Clearingarrangement) error {
	if err := AssertClearingsystemtypevaluesConstraints(obj.ClearingSystem); err != nil {
		return err
	}
	return nil
}
