// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Subject - 
type Subject struct {

	// A thing that is discussed or dealt whit in agreement/arrangement about doing or not doing (as action) something.
	Subject string `json:"Subject,omitempty"`
}

// AssertSubjectRequired checks if the required fields are not zero-ed
func AssertSubjectRequired(obj Subject) error {
	return nil
}

// AssertSubjectConstraints checks if the values respects the defined constraints
func AssertSubjectConstraints(obj Subject) error {
	return nil
}
