// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package openapi




// Rulesettype - 
type Rulesettype struct {

	RuleSetTypeName Name `json:"RuleSetTypeName,omitempty"`

	RuleSetType Rulesettypevalues `json:"RuleSetType,omitempty"`
}

// AssertRulesettypeRequired checks if the required fields are not zero-ed
func AssertRulesettypeRequired(obj Rulesettype) error {
	if err := AssertNameRequired(obj.RuleSetTypeName); err != nil {
		return err
	}
	return nil
}

// AssertRulesettypeConstraints checks if the values respects the defined constraints
func AssertRulesettypeConstraints(obj Rulesettype) error {
	if err := AssertNameConstraints(obj.RuleSetTypeName); err != nil {
		return err
	}
	return nil
}
