// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Leasing
 *
 * The leasing products enables customers to finance equipment purchases using the leased item as collateral when necessary
 *
 * API version: 12.0.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	BQClearingandSettlementAPIService := openapi.NewBQClearingandSettlementAPIService()
	BQClearingandSettlementAPIController := openapi.NewBQClearingandSettlementAPIController(BQClearingandSettlementAPIService)

	BQCollateralAPIService := openapi.NewBQCollateralAPIService()
	BQCollateralAPIController := openapi.NewBQCollateralAPIController(BQCollateralAPIService)

	BQCorporateActionAPIService := openapi.NewBQCorporateActionAPIService()
	BQCorporateActionAPIController := openapi.NewBQCorporateActionAPIController(BQCorporateActionAPIService)

	BQDepositsAPIService := openapi.NewBQDepositsAPIService()
	BQDepositsAPIController := openapi.NewBQDepositsAPIController(BQDepositsAPIService)

	BQFeesAPIService := openapi.NewBQFeesAPIService()
	BQFeesAPIController := openapi.NewBQFeesAPIController(BQFeesAPIService)

	BQFinancialInstrumentAPIService := openapi.NewBQFinancialInstrumentAPIService()
	BQFinancialInstrumentAPIController := openapi.NewBQFinancialInstrumentAPIController(BQFinancialInstrumentAPIService)

	BQInterestAPIService := openapi.NewBQInterestAPIService()
	BQInterestAPIController := openapi.NewBQInterestAPIController(BQInterestAPIService)

	BQIssuedDeviceAPIService := openapi.NewBQIssuedDeviceAPIService()
	BQIssuedDeviceAPIController := openapi.NewBQIssuedDeviceAPIController(BQIssuedDeviceAPIService)

	BQLienAPIService := openapi.NewBQLienAPIService()
	BQLienAPIController := openapi.NewBQLienAPIController(BQLienAPIService)

	BQPaymentsAPIService := openapi.NewBQPaymentsAPIService()
	BQPaymentsAPIController := openapi.NewBQPaymentsAPIController(BQPaymentsAPIService)

	BQSweepAPIService := openapi.NewBQSweepAPIService()
	BQSweepAPIController := openapi.NewBQSweepAPIController(BQSweepAPIService)

	BQWithdrawalsAPIService := openapi.NewBQWithdrawalsAPIService()
	BQWithdrawalsAPIController := openapi.NewBQWithdrawalsAPIController(BQWithdrawalsAPIService)

	CRLeasingFacilityAPIService := openapi.NewCRLeasingFacilityAPIService()
	CRLeasingFacilityAPIController := openapi.NewCRLeasingFacilityAPIController(CRLeasingFacilityAPIService)

	router := openapi.NewRouter(BQClearingandSettlementAPIController, BQCollateralAPIController, BQCorporateActionAPIController, BQDepositsAPIController, BQFeesAPIController, BQFinancialInstrumentAPIController, BQInterestAPIController, BQIssuedDeviceAPIController, BQLienAPIController, BQPaymentsAPIController, BQSweepAPIController, BQWithdrawalsAPIController, CRLeasingFacilityAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
